apiVersion: api.kagent.dev/v1alpha3
kind: ModelConfig
metadata:
  name: anthropic-model-config
  namespace: kagent
spec:
  apiKeySecret: kagent-anthropic
  apiKeySecretKey: ANTHROPIC_API_KEY
  model: claude-sonnet-5-5
  provider: Anthropic
  anthropic: {}
